In [ ]:
import os
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # or any {'0', '1', '2'}
#tf.logging.set_verbosity(tf.logging.ERROR)

use_tpu = False #@param {type:"boolean"}
use_gpu = False #@param {type:"boolean"}
use_cpu = True #@param {type:"boolean"}

if use_tpu:
  
  ## FOR TPU


  if use_tpu:
      assert 'COLAB_TPU_ADDR' in os.environ, 'Missing TPU; did you request a TPU in Notebook Settings?'

  if 'COLAB_TPU_ADDR' in os.environ:
    TF_MASTER = 'grpc://{}'.format(os.environ['COLAB_TPU_ADDR'])
  else:
    TF_MASTER=''
  # Model specific parameters

  # TPU address
  tpu_address = TF_MASTER

  # Number of epochs
  epochs = 50

  # Number of steps_per_epoch
  steps_per_epoch = 5

  # NOTE: Total number of training steps = Number of epochs * Number of steps_per_epochs
  import tensorflow as tf
  print("Tensorflow version " + tf.__version__)

  try:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
    print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
  except ValueError:
    raise BaseException('ERROR: Not connected to a TPU runtime; please see the previous cell in this notebook for instructions!')

  tf.config.experimental_connect_to_cluster(tpu)
  tf.tpu.experimental.initialize_tpu_system(tpu)
  tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)

if use_gpu:
  ## FOR GPU
  #' ' means CPU whereas '/device:G:0' means GPU
  print('using gpu?')
  import tensorflow as tf
  print(tf.test.gpu_device_name())    
  from tensorflow.python.client import device_lib
  #print(device_lib.list_local_devices()) # LIST OF ALL DEVICES AVAILABLE
  #!cat /proc/meminfo    # RAM DETAILS


if use_cpu: 
  !cat /proc/cpuinfo   #RAM DETAILS


processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	:

In [ ]:
!pip install mne pycwt line_profiler nolds entropy  pyhht tsfresh
!pip install -q pyyaml h5py  # Required to save models in HDF5 format


     |████████████████████████████████| 6.8MB 4.3MB/s 
     |████████████████████████████████| 768kB 49.3MB/s 
     |████████████████████████████████| 71kB 8.5MB/s 
     |████████████████████████████████| 92kB 11.1MB/s 
     |████████████████████████████████| 655kB 48.6MB/s 
     |████████████████████████████████| 92kB 10.9MB/s 
     |████████████████████████████████| 102kB 11.4MB/s 
  Created wheel for pycwt: filename=pycwt-0.3.0a22-cp36-none-any.whl size=17808 sha256=954f497b1573e68419b3bc0ff9b9e25ae8eccecd3a1db6e1f48f947cbd0a5921
  Stored in directory: /root/.cache/pip/wheels/e2/e0/b4/311806bd9b792ec6904dbac270666e88912a345730711283af
  Created wheel for entropy: filename=entropy-0.1.5-cp36-none-any.whl size=7199 sha256=736c71ad8c42797bc75b42495c37e4eb42a0c76810728d2b851447da35fd7031
  Stored in directory: /root/.cache/pip/wheels/c7/95/65/359c8b76d79b21ce1e191d6c1afbf451fb100345ea572eb6e8
  Created wheel for contextvars: filename=contextvars-2.4-cp36-none-any.whl size=7666 sha256=18

In [ ]:
!python /content/drive/My\ Drive/Cross-spectrum-EEG/reference_builder.py

{0: 248, 1: 15, 2: 426, 3: 181, 4: 186}
shhs1-200097.edf
shhs1-200097-nsrr.xml
Patient 1:
0 [12] 248
1 [5] 15
2 [210] 426
3 [117] 181
4 [4] 186

{0: 380, 1: 13, 2: 389, 3: 176, 4: 123}
shhs1-200029.edf
shhs1-200029-nsrr.xml
Patient 2:
0 [296] 380
1 [9] 13
2 [285] 389
3 [77] 176
4 [17] 123

{0: 265, 1: 63, 2: 301, 3: 336, 4: 86}
shhs1-200109.edf
shhs1-200109-nsrr.xml
Patient 3:
0 [15] 265
1 [10] 63
2 [43] 301
3 [285] 336
4 [18] 86

{0: 47, 1: 37, 2: 442, 3: 148, 4: 165}
shhs1-200083.edf
shhs1-200083-nsrr.xml
Patient 4:
0 [26] 47
1 [12] 37
2 [131] 442
3 [125] 148
4 [161] 165

{0: 564, 1: 4, 2: 192, 3: 140, 4: 59}
shhs1-200111.edf
shhs1-200111-nsrr.xml
Patient 5:
0 [212] 564
1 [3] 4
2 [55] 192
3 [111] 140
4 [57] 59



In [ ]:
!python /content/drive/My\ Drive/Cross-spectrum-EEG/test_set_builder.py

In [ ]:
!python /content/drive/My\ Drive/Cross-spectrum-EEG/main.py

Streaming output truncated to the last 5000 lines.
[ 0  0  0  0 -1 -1 -1 -1 -1 -1]
Predicted label : 0
Actual label : 1
[ 1  2  3 -1  1  3  1  3  2  3]
Predicted label : 3
Actual label : 1
[-1  2 -1 -1  2 -1 -1  2  2  4]
Predicted label : 2
Actual label : 1
[-1 -1  3  4  2  1  1  3  4  4]
Predicted label : 4
Actual label : 1
[-1 -1  3  4  2  3  4  3  4  3]
Predicted label : 3
Actual label : 1
[ 1  2 -1  4  1  1  4  2  4  4]
Predicted label : 4
Actual label : 1
[ 0  0  0  0  1  1  1 -1 -1 -1]
Predicted label : 0
Actual label : 2
[-1  2 -1  4  2 -1  4  2  4  4]
Predicted label : 4
Actual label : 2
[-1 -1  3  4  2  3  4  3  4  3]
Predicted label : 3
Actual label : 2
[ 1 -1  3 -1  1  1  1  3  2  3]
Predicted label : 1
Actual label : 2
[-1 -1 -1  4 -1  3  4 -1  4  4]
Predicted label : 4
Actual label : 2
[ 0  0  0  0  1 -1 -1 -1 -1 -1]
Predicted label : 0
Actual label : 2
[-1 -1  3  4  2  3  4  3  4  4]
Predicted label : 4
Actual label : 2
[-1 -1  3 -1  2  3  4  3  4  3]
Predicted label : 3


In [ ]:
!python /content/drive/My\ Drive/Cross-spectrum-EEG/base_set_builder.py

patient_no: 20
Time taken so far: 77.0795578956604 seconds
segs: (array([0, 1, 2, 3, 4]), array([ 896,  504, 1407,  480,  513]))
RAM: 1014.7578125 MB


patient_no: 40
Time taken so far: 153.9538917541504 seconds
segs: (array([0, 1, 2, 3, 4]), array([2058, 1265, 2739,  877,  861]))
RAM: 1461.68359375 MB


patient_no: 60
Time taken so far: 234.85275197029114 seconds
segs: (array([0, 1, 2, 3, 4]), array([2970, 2073, 4335, 1247, 1175]))
RAM: 1985.9296875 MB


KeyError: Unscored|9
KeyError: Unscored|9
KeyError: Unscored|9
KeyError: Unscored|9
patient_no: 80
Time taken so far: 317.0246036052704 seconds
segs: (array([0, 1, 2, 3, 4]), array([4079, 2829, 5553, 1696, 1643]))
RAM: 2455.39453125 MB


patient_no: 100
Time taken so far: 398.3193871974945 seconds
segs: (array([0, 1, 2, 3, 4]), array([5003, 3518, 6951, 2171, 2157]))
RAM: 2901.97265625 MB


patient_no: 120
Time taken so far: 483.2002308368683 seconds
segs: (array([0, 1, 2, 3, 4]), array([6068, 4178, 8445, 2568, 2541]))
RAM: 3361.457031

In [ ]:
!python /content/drive/My\ Drive/Cross-spectrum-EEG/dataset_builder0.py

Number of references: 5
Base dataset and references loaded in 21.05301284790039 seconds
REF ID: 0
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
Warning encountered..
*************************
200: Time taken so far is 172.70699048042297 seconds
400: Time taken so far is 334.421

In [ ]:
# CREATE MATRIX MASK OF SHAPE (M,N)

import numpy as np

M=67  #rows
N=3750  #columns

#ROW MASK
a=np.ndarray(shape=(M,N),dtype='int')
for row in range(M):
  for col in range(N):
    a[row][col]=row
print(f'row_mask: {a}')
np.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/row_mask_6.npy',a)
#ROW MASK INVERSE
a=np.ndarray(shape=(M,N),dtype='int')
for row in range(M):
  for col in range(N):
    a[row][col]=M-1-row
print(f'row_mask inverse: {a}')
np.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/row_mask_6_inverse.npy',a)
#COLUMN MASK
a=np.ndarray(shape=(M,N),dtype='int')
for row in range(M):
  for col in range(N):
    a[row][col]=col
print(f'column_mask: {a}')
np.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/column_mask_6.npy',a)
#COLUMN MASK INVERSE
a=np.ndarray(shape=(M,N),dtype='int')
for row in range(M):
  for col in range(N):
    a[row][col]=N-1-col
print(f'row_mask: {a}')
np.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/column_mask_6_inverse.npy',a)



row_mask: [[ 0  0  0 ...  0  0  0]
 [ 1  1  1 ...  1  1  1]
 [ 2  2  2 ...  2  2  2]
 ...
 [64 64 64 ... 64 64 64]
 [65 65 65 ... 65 65 65]
 [66 66 66 ... 66 66 66]]
row_mask inverse: [[66 66 66 ... 66 66 66]
 [65 65 65 ... 65 65 65]
 [64 64 64 ... 64 64 64]
 ...
 [ 2  2  2 ...  2  2  2]
 [ 1  1  1 ...  1  1  1]
 [ 0  0  0 ...  0  0  0]]
column_mask: [[   0    1    2 ... 3747 3748 3749]
 [   0    1    2 ... 3747 3748 3749]
 [   0    1    2 ... 3747 3748 3749]
 ...
 [   0    1    2 ... 3747 3748 3749]
 [   0    1    2 ... 3747 3748 3749]
 [   0    1    2 ... 3747 3748 3749]]
row_mask: [[3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]
 ...
 [3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]]


In [ ]:
NUM_SLEEP_STAGES=5
def split_dataset(data_dict: dict) -> [np.ndarray, list]:
  """
  data_dict -> labelwise dict of (selected_seg_label, avg feature_vector of ref_label: selected_seg X ref_seg)
  """
  X_0, X_1, X_2, X_3, X_4 = ([] for _ in range(NUM_SLEEP_STAGES)) #initializing 5 empty strings
  X = [X_0, X_1, X_2, X_3, X_4]
  
  #features_to_keep = [0,1,2,5,6,7,9,13,16,18,19,20,21,25,26,27,28,29,30,31]
  # features_to_keep = list(range(17))+list(range(24,32))
  # features_to_delete = []
  # for i in range(32):
  #   if i not in features_to_keep:
  #     features_to_delete.append(i) 

  # print(f"Features kept: {features_to_keep}")

  for i in range(NUM_SLEEP_STAGES):
    for tup in data_dict[i]:  
      #x = np.delete(tup[1], 8)
      x = tup[1]       #uncomment if nothing to delete
      X[i].append(x) 

  Y = []
  clf_id = np.random.randint(NUM_SLEEP_STAGES) #emphasizing that it doesn't  matter which ref label we'll use because the label of the randomly selected sample will be same for all keys in the dict
  for tup in data_dict[clf_id]:   
    Y.append(tup[0]) 

  return np.array(X), Y         #(num_sleep_stages, total_samples, num_features), num_samples

test_set = np.load('/content/drive/My Drive/dj6_76f/test_set_balanced_ref5.npy', allow_pickle=True)
test_set_dict = test_set.reshape(-1,1)[0][0]
X_test, Y_test = split_dataset(test_set_dict)
print(np.shape(X_test))
X=[]
for idx in range(5):
  X.append(X_test[idx,:,:])
X_test=np.concatenate((X[0],X[1],X[2],X[3],X[4]),axis=1)
print(np.shape(X_test))

(5, 1984, 75)
(1984, 375)


In [ ]:
# PRINT ALL CHANNEL SIGNAL SAMPLES WRT TIME

import sys
from matplotlib import pyplot as plt

import os
sys.path.append('/content/drive/My Drive/Cross-spectrum-EEG/')
import mne,fnmatch
from xml.etree import ElementTree
import numpy as np
from constants import *
from extract import *

patient_list = sorted(os.listdir(TRAIN_DATA_PATH))
'''
for patient_no in range(NUM_CHOSEN_PATIENTS):
  current_patient = patient_list[patient_no]
  path=TRAIN_DATA_PATH + current_patient
  raw = mne.io.read_raw_edf(path, verbose=False)
  print(raw.ch_names)
  '''
for current_patient in patient_list:
#current_patient = patient_list[0]  
  patient_ann = current_patient[:-4] + '-nsrr.xml'
  ann, onset, duration = extract_anns(TRAIN_ANN_PATH + patient_ann)
  preprocess = None  #getting un-preprocessed segments
#eeg_dict, stat = extract_data(TRAIN_DATA_PATH + current_patient, ann, onset, duration[-1], preprocess=preprocess, return_stats=True)

  path=TRAIN_DATA_PATH + current_patient
  raw = mne.io.read_raw_edf(path, verbose=False)
  print(raw.ch_names)
  no_of_ch=len(raw.ch_names)
  emg_names='*EMG*'
  for name in raw.ch_names:
    if fnmatch.fnmatch(name,emg_names):
      break
  if name!='EMG':
    print(name)
  
    #data=raw.get_data(picks=[name]) 
  '''
  x=data.tolist()[0]
  #print(f'Length of data: {len(x)}')
  #print(x[0:100])
  x=np.array(x)
  #print(f'Mean: {np.mean(x)}')
  #print(f'Std dev: {np.std(x)}')
  print(f'Coeff of variation: {np.std(x)/np.mean(x)}')

  indep_axis=np.linspace(0,len(x)-1,len(x))
  #plt.plot(indep_axis,x,'g',label=name,linewidth=2)
  plt.scatter(indep_axis,x)
  plt.title(f'Channel: {name}')
  plt.ylabel('Signal_value')
  plt.xlabel('Time')
  plt.legend()
  #plt.grid(True, color='k')

  plt.show()
  print()
# PRINT THE SLEEP STAGES OVER TIME:
signal=[]
for i in range(len(onset)-1): 
  try:          
    label = SLEEP_STAGES[ann[i]]
    for j in range(onset[i], onset[i+1]):
        signal.append(label)
      #eeg_dict[label].append(x[j*SAMPLE_RATE:(j+DURATION_OF_EACH_SEGMENT)*SAMPLE_RATE])
  except KeyError:
    print(f"KeyError: {ann[i]}")
    pass
#TAKING CARE OF THE LAST SEGMENT 
#try-except for the weird 'Unscored-9' stage in some patients
indep_axis=np.linspace(0,len(signal)-1, len(signal))
plt.scatter(indep_axis,signal,label='stages')

plt.title('Sleep stages')
plt.ylabel('Y-axis')
plt.xlabel('X-axis')
plt.legend()
#plt.grid(True, color='k')

plt.show()
'''

['SaO2', 'H.R.', 'EEG(sec)', 'ECG', 'EMG', 'EOG(L)', 'EOG(R)', 'EEG', 'THOR RES', 'ABDO RES', 'POSITION', 'LIGHT', 'NEW AIR', 'OX stat']
['SaO2', 'H.R.', 'EEG(sec)', 'ECG', 'EMG', 'EOG(L)', 'EOG(R)', 'EEG', 'THOR RES', 'ABDO RES', 'POSITION', 'LIGHT', 'AIRFLOW', 'OX stat']
['SaO2', 'H.R.', 'EEG(sec)', 'ECG', 'EMG', 'EOG(L)', 'EOG(R)', 'EEG', 'THOR RES', 'ABDO RES', 'POSITION', 'LIGHT', 'NEW AIR', 'OX stat']
['SaO2', 'H.R.', 'EEG(sec)', 'ECG', 'EMG', 'EOG(L)', 'EOG(R)', 'EEG', 'THOR RES', 'ABDO RES', 'POSITION', 'LIGHT', 'AIRFLOW', 'OX stat']
['SaO2', 'H.R.', 'EEG(sec)', 'ECG', 'EMG', 'EOG(L)', 'EOG(R)', 'EEG', 'SOUND', 'AIRFLOW', 'THOR RES', 'ABDO RES', 'POSITION', 'LIGHT', 'AUX', 'OX stat']
['SaO2', 'H.R.', 'EEG(sec)', 'ECG', 'EMG', 'EOG(L)', 'EOG(R)', 'EEG', 'SOUND', 'AIRFLOW', 'THOR RES', 'ABDO RES', 'POSITION', 'LIGHT', 'AUX', 'OX stat']
['SaO2', 'H.R.', 'EEG(sec)', 'ECG', 'EMG', 'EOG(L)', 'EOG(R)', 'EEG', 'SOUND', 'AIRFLOW', 'THOR RES', 'ABDO RES', 'POSITION', 'LIGHT', 'NEW AIR', 

KeyboardInterrupt: ignored

In [ ]:

import sys
from matplotlib import pyplot as plt

import os
sys.path.append('/content/drive/My Drive/Cross-spectrum-EEG/')
path = '/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/'
row_mask = np.load(path + 'row_mask_6.npy', allow_pickle=True)  #mask matrices have fixed shape for same scale and time i.shape/j.shape=(263,3750)
column_mask = np.load(path + 'column_mask_6.npy', allow_pickle=True) 
type(row_mask)
type(column_mask)

numpy.ndarray

In [ ]:
for i in range(67):
  for j in range(3750):
    column_mask[i][j]=3749-j
print(column_mask)
np.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/column_mask_6_inverse.npy',column_mask)


[[3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]
 ...
 [3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]
 [3749 3748 3747 ...    2    1    0]]


In [ ]:
# COMPARING WAVELET LIBRARIES

import numpy as np
import pycwt as wavelet
from sklearn.metrics.pairwise import cosine_similarity
import timeit
from scipy.stats import kurtosis, skew, moment, trim_mean

def xwt(s1,s2,dt=1,DJ=6):
  W_complex, _, _, _ = wavelet.xwt(s1, s2, dt, dj=1/DJ)   

ref_segments = np.load('/content/drive/My Drive/Cross-spectrum-EEG/datasets/ref-EEG/reference_segments_5_EEG_channel.npy', allow_pickle=True).reshape(-1, 1)[0][0]
s2=np.array(ref_segments[0][0])

base_dataset = np.load('/content/drive/My Drive/data_set2.npy', allow_pickle=True)
s1=np.array(base_dataset[0][1])

assert np.shape(s1)==np.shape(s2)

print(np.shape(s1))
print(np.shape(s2))

#import random
!pip install piwavelet
import numpy as np
timeit.timeit('W_complex, _, _, _ = piwavelet.wcross(s1, s2,)',setup='from piwavelet import piwavelet; import pycwt as wavelet; import numpy as np; s1=np.random.rand(3750); s2=np.random.rand(3750)',number = 100)

(3750,)
(3750,)


In [ ]:
import numpy as np
d=np.load('/content/drive/My Drive/data_set2(EMG).npy', allow_pickle=True)
np.shape(d)

(32000, 2)

In [ ]:
import numpy as np
for i in [0,1,2,3,4]:
  d=np.load(f'/content/drive/My Drive/ref5_dj6/clf{i}_2.npy',allow_pickle=True)
  print(np.shape(d))

(13479, 2)
(18225, 2)
(11996, 2)
(11481, 2)
(17584, 2)


In [ ]:
# PRINT SHAPE OF TRAINSETS
import numpy as np
for i in [0,1,2,3,4]:
  d=np.load(f'/content/drive/My Drive/ref5_dj6/clf{i}_EMG.npy',allow_pickle=True)
  print(np.shape(d))

(31908, 2)
(31908, 2)
(31908, 2)
(31908, 2)
(31463, 2)


In [ ]:
13479+18507

31986

In [ ]:
18225+13760

31985

In [ ]:
11996+19992

31988

In [ ]:
11481+20507

31988

In [ ]:
17584+14401

31985

In [ ]:
# CONCATENATE TWO ARRAYS

import numpy as np
for i in [0,1,2,3,4]:
  d=np.load(f'/content/drive/My Drive/ref5_dj6/clf{i}.npy',allow_pickle=True)
  e=np.load(f'/content/drive/My Drive/ref5_dj6/clf{i}_2.npy',allow_pickle=True)
  f=np.concatenate((d,e),axis=0)
  print(np.shape(f))
  np.save(f'/content/drive/My Drive/ref5_dj6/clf{i}_0.npy',f)



(31986, 2)
(31985, 2)
(31988, 2)
(31988, 2)
(31985, 2)


In [ ]:
#EXTRACT X AND Y FROM THE DATASETS

data_list=[]
for i in range(5):
  data_list.append(np.load(f'/content/drive/My Drive/ref5_dj6/clf{i}_0.npy', allow_pickle=True)[0:31985,:])

X=[]
for i in range(5):
  X.append(np.array(list(data_list[i])))
  X[i] = np.stack([x for x in X[i]])
  print(np.shape(X[i]))


# FIND FIRST POINT OF DIFFERENCES IN THE 5 DATASETS:
'''

flag=0
for seg in range(31985):
  y_labels=[]
  for label in range(5):
    y_labels.append(Y[label][seg])
  item=y_labels[0]
  for idx,x in enumerate(y_labels):
    if item!=x:
      print(seg,end=' ')
      print(idx)
      flag=1
      break
  if flag==1:
    break

'''



(31985, 2)
(31985, 2)
(31985, 2)
(31985, 2)
(31985, 2)


"\n\nflag=0\nfor seg in range(31985):\n  y_labels=[]\n  for label in range(5):\n    y_labels.append(Y[label][seg])\n  item=y_labels[0]\n  for idx,x in enumerate(y_labels):\n    if item!=x:\n      print(seg,end=' ')\n      print(idx)\n      flag=1\n      break\n  if flag==1:\n    break\n\n"

In [ ]:
for i in range(5):
  #print(X[i][31960:31971])
  print(np.shape(X[i]))
  np.save(f'/content/drive/My Drive/ref5_dj6/clf{i}_',X[i])

(31973, 2)
(31974, 2)
(31971, 2)
(31971, 2)
(31974, 2)


In [ ]:
for i in range(14):
  X[3]=np.delete(X[3],20508,axis=0)

In [ ]:
for i in range(14):
  X[2]=np.delete(X[2],19992,axis=0)

In [ ]:
for i in range(12):
  X[0]=np.delete(X[0],18507,axis=0)

In [ ]:
for i in range(11):
  X[4]=np.delete(X[4],14397,axis=0)

In [ ]:
for i in range(2):
  X[1]=np.delete(X[1],13759,axis=0)

In [ ]:
for i in range(9):
  X[1]=np.delete(X[1],13760,axis=0)

In [ ]:
# MAKING ROW AND COLUMN MASKS OF SMALLER SHAPES:

import numpy as np
path = '/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/'
inv=False
if inv==True:  
    row_mask = np.load(path + 'row_mask_6_inverse.npy', allow_pickle=True)  #mask matrices have fixed shape for same scale and time i.shape/j.shape=(263,3750)
    column_mask = np.load(path + 'column_mask_6_inverse.npy', allow_pickle=True) 
else: 
    row_mask = np.load(path + 'row_mask_6.npy', allow_pickle=True)  #mask matrices have fixed shape for same scale and time i.shape/j.shape=(263,3750)
    column_mask = np.load(path + 'column_mask_6.npy', allow_pickle=True) 
print(row_mask)
print(column_mask)
'''
row_mask=row_mask[:,0:938]
np.shape(row_mask)

column_mask=column_mask[:,0:938]
np.shape(column_mask)

np.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/row_mask_6.npy',row_mask)
np.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/column_mask_6.npy',column_mask)
'''

[[ 0  0  0 ...  0  0  0]
 [ 1  1  1 ...  1  1  1]
 [ 2  2  2 ...  2  2  2]
 ...
 [64 64 64 ... 64 64 64]
 [65 65 65 ... 65 65 65]
 [66 66 66 ... 66 66 66]]
[[  0   1   2 ... 935 936 937]
 [  0   1   2 ... 935 936 937]
 [  0   1   2 ... 935 936 937]
 ...
 [  0   1   2 ... 935 936 937]
 [  0   1   2 ... 935 936 937]
 [  0   1   2 ... 935 936 937]]


"\nrow_mask=row_mask[:,0:938]\nnp.shape(row_mask)\n\ncolumn_mask=column_mask[:,0:938]\nnp.shape(column_mask)\n\nnp.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/row_mask_6.npy',row_mask)\nnp.save('/content/drive/My Drive/Cross-spectrum-EEG/datasets/matrix_masks/column_mask_6.npy',column_mask)\n"

In [ ]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()


11493376/11490434 [==============================] - 0s 0us/step
[5 0 4 ... 5 6 8]


In [ ]:
import numpy as np
print(np.unique(np.array(y_train),return_counts=True ))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8), array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]))


In [ ]:
np.shape(y_test)

(10000,)

In [ ]:
model = tf.keras.models.Sequential([

      tf.keras.layers.Flatten(input_shape=(28, 28)),
      tf.keras.layers.Dense(512, activation=tf.nn.relu),
      tf.keras.layers.Dense(10, activation=tf.nn.softmax)

    ])
model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])


In [ ]:
model.fit(x_train, y_train, epochs=1)

1875/1875 [==============================] - 6s 3ms/step - loss: 2.6329 - accuracy: 0.9033


In [ ]:
np.shape(x_train)

(60000, 28, 28)

In [ ]:
np.shape(y_train)

(60000,)